# Generated by Django 5.2.6 on 2025-10-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_professional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='professional',
            field=models.IntegerField(),
        ),
    ]
